name: Build and Deploy EduFlow (Spring Boot Maven)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Spring Boot Project
        run: mvn clean package -DskipTests

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${DOCKER_USER}/eduflow:${IMAGE_TAG} -t ${DOCKER_USER}/eduflow:latest .
          docker push ${DOCKER_USER}/eduflow:${IMAGE_TAG}
          docker push ${DOCKER_USER}/eduflow:latest

  deploy:
    name: Deploy EduFlow to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          SCP_PASSWORD: ${{ secrets.SCP_PASSWORD }}
          SCP_USERNAME: ${{ secrets.SCP_USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          sshpass -p "${SCP_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SCP_USERNAME}@${SERVER_IP} << EOF

          echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin

          docker pull ${DOCKER_USER}/eduflow:latest

          docker stop eduflow || true
          docker rm eduflow || true

          docker run -d \
            --name eduflow \
            --network app-network \
            --restart always \
            -p 8099:8099 \
            -e SPRING_PROFILES_ACTIVE=prod \
            ${DOCKER_USER}/eduflow:latest

          EOF
